-- Schema for the case service. Kept portable between PostgreSQL and H2 (PostgreSQL mode):
-- identity columns instead of BIGSERIAL, JSON stored as TEXT.

CREATE TABLE alert (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id        VARCHAR(128)   NOT NULL,
    tx_id           BIGINT         NOT NULL,
    event_ts        TIMESTAMP WITH TIME ZONE NOT NULL,
    from_account    VARCHAR(64)    NOT NULL,
    to_account      VARCHAR(64)    NOT NULL,
    amount_usd      NUMERIC(19, 2) NOT NULL,
    currency        VARCHAR(32),
    payment_format  VARCHAR(32),
    score           DOUBLE PRECISION NOT NULL,
    threshold       DOUBLE PRECISION,
    model_version   VARCHAR(64),
    ring_id         VARCHAR(64),
    detector_names  VARCHAR(512),
    evidence_json   TEXT           NOT NULL,
    received_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_alert_alert_id UNIQUE (alert_id)
);
CREATE INDEX ix_alert_ring_id ON alert (ring_id);

CREATE TABLE alert_account (
    alert_pk    BIGINT      NOT NULL REFERENCES alert (id),
    account_id  VARCHAR(64) NOT NULL,
    role        VARCHAR(8)  NOT NULL,
    CONSTRAINT pk_alert_account PRIMARY KEY (alert_pk, account_id, role)
);
CREATE INDEX ix_alert_account_account ON alert_account (account_id);

CREATE TABLE investigation_case (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(32),
    status            VARCHAR(20)    NOT NULL,
    disposition       VARCHAR(32),
    priority          VARCHAR(10)    NOT NULL,
    max_score         DOUBLE PRECISION NOT NULL,
    alert_count       INTEGER        NOT NULL,
    total_amount_usd  NUMERIC(19, 2) NOT NULL,
    assignee          VARCHAR(64),
    merged_into_id    BIGINT REFERENCES investigation_case (id),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at         TIMESTAMP WITH TIME ZONE,
    version           BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT uq_case_reference UNIQUE (reference)
);
CREATE INDEX ix_case_status ON investigation_case (status);

CREATE TABLE case_account (
    case_id     BIGINT      NOT NULL REFERENCES investigation_case (id),
    account_id  VARCHAR(64) NOT NULL,
    CONSTRAINT pk_case_account PRIMARY KEY (case_id, account_id)
);
CREATE INDEX ix_case_account_account ON case_account (account_id);

CREATE TABLE case_alert (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id      BIGINT NOT NULL REFERENCES investigation_case (id),
    alert_pk     BIGINT NOT NULL REFERENCES alert (id),
    attached_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_case_alert_alert UNIQUE (alert_pk)
);
CREATE INDEX ix_case_alert_case ON case_alert (case_id);

CREATE TABLE audit_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id      BIGINT        NOT NULL REFERENCES investigation_case (id),
    actor        VARCHAR(64)   NOT NULL,
    action       VARCHAR(32)   NOT NULL,
    from_status  VARCHAR(20),
    to_status    VARCHAR(20),
    details      VARCHAR(4000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_event_case ON audit_event (case_id, id);

CREATE TABLE report (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id           BIGINT       NOT NULL REFERENCES investigation_case (id),
    report_type       VARCHAR(32)  NOT NULL,
    content_type      VARCHAR(64)  NOT NULL,
    entity_reference  VARCHAR(64)  NOT NULL,
    sha256            VARCHAR(64)  NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    generated_by      VARCHAR(64)  NOT NULL,
    generated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_report_case ON report (case_id);

CREATE TABLE filing_request (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id           BIGINT        NOT NULL REFERENCES investigation_case (id),
    report_id         BIGINT        NOT NULL REFERENCES report (id),
    status            VARCHAR(16)   NOT NULL,
    requested_by      VARCHAR(64)   NOT NULL,
    requested_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    request_comment   VARCHAR(2000),
    decided_by        VARCHAR(64),
    decided_at        TIMESTAMP WITH TIME ZONE,
    decision_comment  VARCHAR(2000),
    version           BIGINT        NOT NULL DEFAULT 0
);
CREATE INDEX ix_filing_request_case ON filing_request (case_id);
