import {App,h,button,field,select,row,form,modal,table,panel,metrics,money,badge,date,short,dl,download,notice} from './shared.js';
const app=new App({project:'mule-ring-detector',title:'Mule Ring Detector',abbr:'MR',accent:'#805e1c',tagline:'Follow the evidence. Work the case.',description:'Score transactions, investigate connected accounts, record decisions, and move STR filings through independent review.',views:[['overview','Overview'],['cases','Case queue'],['monitoring','Transaction monitoring'],['reports','Reports'],['activity','Activity']]});
let graphInstance=null,graphObserver=null;
const name=id=>id==='engine'?'Detection engine':app.session.members.find(m=>'u_'+m.id===id)?.name||id||'Unassigned';
async function loadEvidence(){const d=modal('Import sample evidence',notice('Import 50 alerts scored by the Rust detection model from the checked-in synthetic dataset. They become editable cases in your workspace.'),form([],'Import evidence',async()=>{await app.action('evidence/import',{},'Evidence imported.');d.close();await app.reload();app.go('cases');}));}
const caseRows=items=>items.map(c=>[c.reference,badge(c.status),badge(c.priority),c.maxScore.toFixed(3),c.alertCount,c.accounts.length,money(c.totalAmountUsd*100),name(c.assignee),button('Open',()=>app.go('case-'+c.id),'secondary small')]);
async function exportReport(id,type){try{download(await app.request(`cases/${id}/${type}`,{blob:true}),`case-${id}-${type}`);app.toast('Report generated.');await app.reload();}catch(e){app.toast(e.message,'error');}}
function graph(el,g){if(graphObserver)graphObserver.disconnect();if(graphInstance)graphInstance.destroy();if(!window.cytoscape){el.replaceChildren(notice('The graph library is still loading. Use Refresh to retry.'));return;}const colors={source:'#b54c42',intermediary:'#b58a31',sink:'#326a9e',member:'#8395a3'};graphInstance=window.cytoscape({container:el,elements:[...g.nodes.map(n=>({data:{id:n.id,label:n.label.replace(/^[a-f0-9]{16}-/,''),color:colors[n.role]||colors.member}})),...g.edges.map((e,i)=>({data:{id:'e'+i,source:e.source,target:e.target,alerted:e.alerted?1:0,label:e.detector}}))],style:[{selector:'node',style:{'background-color':'data(color)',label:'data(label)','font-size':9,width:18,height:18,'text-valign':'bottom','text-margin-y':4}},{selector:'edge',style:{width:1.5,'line-color':'#b7c4ce','target-arrow-color':'#b7c4ce','target-arrow-shape':'triangle','curve-style':'bezier'}},{selector:'edge[alerted = 1]',style:{width:2.5,'line-color':'#b54c42','target-arrow-color':'#b54c42'}}],layout:{name:g.nodes.length>40?'concentric':'cose',animate:false,padding:24}});graphObserver=new ResizeObserver(()=>{if(graphInstance){graphInstance.resize();graphInstance.fit(undefined,24);}});graphObserver.observe(el);}
function actionForm(c,action,label,fields,success){const d=modal(label,form(fields,label,async b=>{await app.action(`cases/${c.id}/${action}`,b,success);d.close();await app.reload();}));}
function caseView(c){const actions=[button('Back to queue',()=>app.go('cases'),'secondary'),button('Refresh',()=>app.reload(),'secondary')],active=['OPEN','INVESTIGATING','ESCALATED'].includes(c.status),pending=c.filingRequest?.status==='PENDING';const comments=textareaComment(c);
 if(active&&c.assignee!=='u_'+app.session.id)actions.push(button('Assign to me',async()=>{try{await app.action(`cases/${c.id}/assign`,{},'Case assigned.');await app.reload();}catch(e){app.toast(e.message,'error');}}));
 const transitions=h('div',{class:'actions'});
 if(!pending)for(const to of c.allowedTransitions){if(to==='CLOSED')transitions.append(button('Close case',()=>actionForm(c,'transition','Close case',[h('input',{type:'hidden',name:'to',value:'CLOSED'}),select('disposition','Disposition',[['NO_FURTHER_ACTION','No further action'],['FALSE_POSITIVE','False positive']]),field('comment','Decision note',{maxLength:2000})],'Case closed.'),'danger'));else transitions.append(button(to==='ESCALATED'?'Escalate':'Start investigation',()=>actionForm(c,'transition',to==='ESCALATED'?'Escalate case':'Start investigation',[h('input',{type:'hidden',name:'to',value:to}),field('comment','Decision note',{maxLength:2000})],'Case updated.'),'secondary'));}
 const review=h('div',{});
 if(c.status==='ESCALATED'&&!pending)review.append(notice('Generate the STR XML, then request an independent supervisor review.'),button('Request filing review',()=>actionForm(c,'filing-request','Request filing review',[field('comment','Review note',{maxLength:2000})],'Filing requested.')));
 if(pending){review.append(notice('Awaiting supervisor review. Requested by '+name(c.filingRequest.requestedBy)+'.'));if(app.session.role==='SUPERVISOR'&&c.filingRequest.requestedBy!=='u_'+app.session.id)review.append(h('div',{class:'actions'},button('Approve filing',()=>actionForm(c,'filing-approval','Approve STR filing',[field('comment','Approval note',{maxLength:2000})],'Filing approved.')),button('Reject filing',()=>actionForm(c,'filing-rejection','Reject STR filing',[field('reason','Rejection reason',{maxLength:2000})],'Filing rejected.'),'danger')));}
 const graphHost=h('div',{class:'graph','aria-label':'Account evidence graph'}),auditHost=h('div',{},h('p',{class:'muted'},'Loading audit trail…'));
 setTimeout(async()=>{try{const [g,a]=await Promise.all([app.request(`cases/${c.id}/graph`),app.request(`cases/${c.id}/audit`)]);if(graphHost.isConnected)graph(graphHost,g);if(auditHost.isConnected)auditHost.replaceChildren(h('ol',{class:'timeline'},a.map(e=>h('li',{},h('strong',{},e.action.replaceAll('_',' ')),h('p',{},e.details||''),h('small',{},date(e.timestamp)+' · '+name(e.actor))))));}catch(e){if(graphHost.isConnected)graphHost.replaceChildren(notice(e.message,'error'));}},0);
 return [app.head(c.reference,'Case evidence, decisions, and a complete audit history.',actions),metrics([['Risk score',c.maxScore.toFixed(3),c.priority+' priority'],['Alerts',c.alertCount,c.status],['Accounts',c.accounts.length,'Connected accounts'],['Total value',money(c.totalAmountUsd*100),'USD across alerts']]),h('div',{class:'columns'},panel('Evidence graph',graphHost,h('p',{class:'muted'},'Sources → intermediaries → sinks. Red edges identify alerted transactions.')),panel('Case workflow',dl([['Status',badge(c.status)],['Assignee',name(c.assignee)],['Disposition',c.disposition||'—'],['Ring IDs',c.ringIds.map(short).join(', ')||'—']]),h('br'),transitions,h('br'),review,h('br'),h('div',{class:'actions'},button('STR XML',()=>exportReport(c.id,'str.xml'),'secondary'),button('Summary HTML',()=>exportReport(c.id,'summary.html'),'secondary'),button('Summary PDF',()=>exportReport(c.id,'summary.pdf'),'secondary')))),panel('Alerts',table(['Timestamp','Alert','From account','To account','Amount USD','Score','Detectors'],c.alerts.map(a=>[date(a.timestamp),short(a.alertId),short(a.fromAccount),short(a.toAccount),money(a.amountUsd*100),a.score.toFixed(3),a.detectors.join(', ')]))),h('div',{class:'columns equal'},panel('Add a case note',comments),panel('Audit trail',auditHost))];}
function textareaComment(c){return form([h('label',{class:'field'},'Comment',h('textarea',{name:'text',required:true,maxLength:2000,placeholder:'Record your observations and next steps.'}))],'Add note',async b=>{await app.action(`cases/${c.id}/comments`,b,'Note added.');await app.reload();});}
app.renderView=(page,d)=>{
 if(graphObserver)graphObserver.disconnect();if(graphInstance){graphInstance.destroy();graphInstance=null;}
 if(page.startsWith('case-')){const c=d.cases.find(c=>c.id===Number(page.slice(5)));return c?caseView(c):[app.head('Case not found','This case does not belong to your current workspace.'),button('Back to queue',()=>app.go('cases'))];}
 if(page==='cases'){const holder=h('div',{}),filter=select('status','Status',[['ALL','All cases'],['ACTIVE','Active cases'],['OPEN','Open'],['INVESTIGATING','Investigating'],['ESCALATED','Escalated'],['CLOSED','Closed'],['MERGED','Merged']],'ACTIVE');const draw=()=>{const value=filter.querySelector('select').value;const cases=d.cases.filter(c=>value==='ALL'||value==='ACTIVE'&&['OPEN','INVESTIGATING','ESCALATED'].includes(c.status)||c.status===value);holder.replaceChildren(table(['Case','Status','Priority','Score','Alerts','Accounts','Total USD','Assignee',''],caseRows(cases),'No cases match this queue. Import evidence or score new transactions.'));};filter.querySelector('select').addEventListener('change',draw);draw();return [app.head('Case queue','Prioritize risk, assign investigations, and record decisions.',[d.cases.length===0?button('Import sample evidence',loadEvidence):button('Refresh',()=>app.reload(),'secondary')]),panel('',filter,h('br'),holder)];}
 if(page==='monitoring'){const result=h('div',{}),history=h('div',{});const drawHistory=()=>history.replaceChildren(table(['When','From','To','Amount USD','Score','Threshold','Result'],app.data.scores.map(s=>[date(s.timestamp),s.fromAccount,s.toAccount,money(s.amount*100),s.score.toFixed(4),s.threshold.toFixed(4),badge(s.alert?'FLAGGED':'CLEAR')])));drawHistory();return [app.head('Transaction monitoring','Score a transfer through the Rust model. Flagged transactions create cases in your workspace.'),h('div',{class:'columns equal'},panel('Score a transaction',form([row(field('fromAccount','From account',{maxLength:24,placeholder:'ACCT-1001'}),field('toAccount','To account',{maxLength:24,placeholder:'ACCT-1002'})),row(field('amount','Amount USD',{type:'number',min:'.01',step:'.01'}),select('paymentFormat','Payment method',['ACH','Wire','Cash','Cheque','Credit Card'])),field('timestamp','Timestamp',{type:'datetime-local',value:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)})],'Score transaction',async b=>{b.timestamp=new Date(b.timestamp).toISOString();const r=await app.action('transactions/score',b);result.replaceChildren(panel('Scoring result',dl([['Score',r.score.toFixed(4)],['Threshold',r.threshold.toFixed(4)],['Outcome',badge(r.alert?'FLAGGED':'CLEAR')],['Latency',r.latencyUs.toFixed(1)+' µs']]),h('p',{class:'muted'},'A score is an investigation signal, not a confirmed finding.')));app.data=await app.request('state');drawHistory();})),result),panel('Scoring history',history)];}
 if(page==='reports'){const reports=d.cases.flatMap(c=>c.reports.map(r=>({c,r})));return [app.head('Reports','Generated reports and independent STR filing review.'),panel('',table(['Case','Report type','Generated','Status',''],reports.map(({c,r})=>[c.reference,r.type,date(r.createdAt||r.generatedAt),badge(c.filingRequest?.status||c.status),button('Open case',()=>app.go('case-'+c.id),'secondary small')]),'Open a case to generate its STR XML or investigation summary.'))];}
 if(page==='activity')return [app.head('Activity','Your workspace investigation operations.'),app.activity()];
 const active=d.cases.filter(c=>['OPEN','INVESTIGATING','ESCALATED'].includes(c.status));return [app.head('Overview','The investigation queue and model-scored evidence for your team.',[d.cases.length?button('Refresh',()=>app.reload(),'secondary'):button('Import sample evidence',loadEvidence)]),metrics([['Active cases',active.length,'Open, investigating, or escalated'],['Critical cases',active.filter(c=>c.priority==='CRITICAL').length,'Highest-priority investigations'],['Alerts',d.cases.reduce((n,c)=>n+c.alertCount,0),'Attached to cases'],['Awaiting review',d.cases.filter(c=>c.filingRequest?.status==='PENDING').length,'Independent supervisor decision']]),panel('Priority queue',table(['Case','Status','Priority','Score','Alerts','Accounts','Total USD','Assignee',''],caseRows([...active].sort((a,b)=>b.maxScore-a.maxScore).slice(0,8)),'Import the model-scored sample dataset or score a new transaction to begin.')),notice('Your cases are private to your workspace. Invite another account as supervisor to complete an independent filing review.')];
};app.start();
